### ISSUE TITLE
History saved only on product update

### ISSUE THREAD

**Issue by kkarpieszuk** [kkarpieszuk/wc-price-history#28]
Reported here https://wordpress.org/support/topic/not-working-properly-146/

After the installation plugin does not show history at all because it is saved only on product update. 

Possible solution:
- on minimal display, if checked that history does not exist, update it with the current price

**Comment by doghi22** [comment]
I think by default when the plugin is installed should add to the price history the actual price.

Hello, thx for solving my ticket :).

**Comment by kkarpieszuk** [comment]
@doghi22 thank you for the suggestion. On the sites where the amount of products is reasonable, it makes sense, but if the site has 1000s of products installation process would take several minutes if not failed because max execution time limit. 

I could add some migration logic but this would impact users' experience. 

Instead, I am going to apply this logic per product only at the moment product tries to obtain the history for the first time. If the history is empty, it will set current price as the first element of the history and save it.

**Comment by kkarpieszuk** [comment]
@doghi22 good news, fix is already saved. I will add fix for your other issue as well and then I will release 1.5 with both fixes :)

**Comment by doghi22** [comment]
Niceee, im waiting for 1.5 release then. Is coming today? :D

**Comment by kkarpieszuk** [comment]
@doghi22 it is released already with both fixes ;)

**Comment by doghi22** [comment]
Yeap. working good but i found another problem.

On product page at similar products the price is displayed, and i choose to show it only on product page.

[Link](https://rucsac-arctichunter.ro/produs/portofel-arctic-hunter-orizontal-cu-capsa-pentru-carduri-negru-model-ahq013/).

**Comment by doghi22** [comment]
Also on main page are displayed. I think its displayed on every elemend added with wpbakery. 

In my settings is setup to show the price only in product page.

**Comment by kkarpieszuk** [comment]
@doghi22 thank you for finding this

For the upsell/related products, I just fixed it here https://github.com/kkarpieszuk/wc-price-history/issues/32 . It will be released as 1.6

For the incompatibilities with WP Bakery I am affraid I can't handle it :( I see it is proprietary tool and as WC Price History is free I can't invest money to fix issues. Please try to get any feedback from WP Bakery authors; maybe they can fix this on their end or they could help with their own pull reuqest to WC Price History (you can share with them the url to this issue; the repository is open and I am accepting 3rd parties code submissions)

**Comment by kkarpieszuk** [comment]
1.6 with the fix for related/upsell product has been released to wp repo :)
