### ISSUE TITLE
Lowest price displayed without tax in spite of WooCommerce settings

### ISSUE THREAD

**Issue by mziab** [kkarpieszuk/wc-price-history#34]
I've noticed that the lowest price (using the shortcode) is displayed without tax, despite the following WooCommerce tax settings:
"Prices entered with tax" -> "No, I will enter prices exclusive of tax"
"Display prices in the shop" -> "Including tax"
"Display prices during cart and checkout" -> "Including tax"

Behavior:
The price is displayed without tax

Expected behavior:
The price is displayed with tax included

Relevant package versions:
WooCommerce 7.3.0
WC Price History 1.6.1

**Comment by kkarpieszuk** [comment]
thanks, let me fix this

**Comment by mziab** [comment]
@kkarpieszuk There seems to be a regression in 1.6.2:

`Fatal error: Uncaught Error: Class 'PriorPrice\Taxes' not found in ANONYMIZED/wp-content/plugins/wc-price-history/app/PriorPrice/Hooks.php:19 Stack trace: #0 ANONYMIZED/wp-content/plugins/wc-price-history/plugin.php(33): PriorPrice\Hooks->register_hooks() #1 ANONYMIZED/wp-admin/includes/plugin.php(2314): include_once('/home/ddd/ftp/w...') #2 ANONYMIZED/wp-admin/plugins.php(192): plugin_sandbox_scrape('wc-price-histor...') #3 {main} thrown in ANONYMIZED/wp-content/plugins/wc-price-history/app/PriorPrice/Hooks.php on line 19
`

**Comment by kkarpieszuk** [comment]
sorry for that, I just learned in a hard way wordpress is still using the plugin on the time when it is being upgraded :( sorry that you had to learn it with me

I release 1.6.4, please download it and install

**Comment by kkarpieszuk** [comment]
wait, it is still wrong... (what a day...)

**Comment by kkarpieszuk** [comment]
It should be ok now, please download 1.6.4

**Comment by mziab** [comment]
Thanks, it seems to be working as expected.

**Comment by kkarpieszuk** [comment]
uff, the fault was completely on my own. I created a new `Taxes.php` class but I forgot when you upload ne wversion of the plugin to WordPress repository server you have to explicitly mark a new files to be uploaded. That's why I have seen this fixed (I have this file on my comp of course) but you had fatal error (required Taxes.php file was not on wordpress repo).
