### ISSUE TITLE
issue with price when using [wc_price_history]

### ISSUE THREAD

**Issue by skazareli** [kkarpieszuk/wc-price-history#38]
Hello,

first of all, thanks for the excellent work with the plugin =)

I found the issue with displaying prices when using shortcode [wc_price_history]. 

My settings in woo: 12,90 €
[wc_price_history] is displaying: 12.9 € -> with a dot . and without 2 decimals. 

Thanks 
Simon

**Comment by kkarpieszuk** [comment]
Hello

thank you for using my plugin and reporting the issue!

In fact that was reported two days ago in #36 and it will be fixed soon. The #36 ticket is about wrong decimal number but I see I accidentally fixed separator as well :)

I will be releasing a new version probably today.

**Comment by kkarpieszuk** [comment]
hello @skazareli 1.6.5 fixing your issue has been released

if you want to appreciate quick fix, please consider rating 5-start for my plugin in WordPress repo: https://wordpress.org/support/plugin/wc-price-history/reviews/?filter=5#new-post

**Comment by skazareli** [comment]
Great, thank you! 

Regards, 
Skazareli
