### ISSUE TITLE
[Feature request] Update main lowes price for variable products on variant change

### ISSUE THREAD

**Issue by kkarpieszuk** [kkarpieszuk/wc-price-history#48]
**Describe the solution you'd like**
From here https://wordpress.org/support/topic/doesnt-seperate-product-variations/

**Steps to see the problem**

https://www.youtube.com/watch?v=MGI2puTPUqY

---------------
Hint: Are you waiting for the same feature to be implemented? Please react with ❤️ to this issue description (features with more reactions will get higher priority)

**Comment by beachboy00** [comment]
Hi Konrad, this would be very important and useful to be able to continue using the plugin. Thanks for the great work!
