### ISSUE TITLE
Creating new products via duplicate - addon shows duplicated product price on new product

### ISSUE THREAD

**Issue by Venduo** [kkarpieszuk/wc-price-history#50]
Hi there,

First of all thank you for this wonderful addon!
Secondly I have some issue and would like to know if there's a workaround.
Since I have a custom template for products, I generally just duplicate product and change the txt/pictures/price and publish it..
But it seems that the addon is picking up the initial price when the product was duplicated prior to publishing it and now when I try to put the discount price it posts the price from the initial duplicated product.
Any thoughts on how to solve this? since I don't have a blank template (the one without the pricing on it) and that wasn't published.
Thanks in advance!

**Comment by Venduo** [comment]
Thanks for the quick response. 
Yeah it would be easier to just create a template for the new product without the price and just start from there.
Just tested it out and it works perfectly.
Thank you once more and have a nice weekend.

**Comment by kkarpieszuk** [comment]
Hi @Venduo :) just to clarify :) I see you had chat with a chatbot which I installed a few days ago to help me review my pull requests and I was not aware it also replies to github issues but I see now it does :) This is some chat based on chatgpt and I am quite impressed it gave you quite correct hints :) 

As a human, let me explain: wc price history plugin hooks into the process of saving the product (and when you duplicate product, WP saves the product so WC Price History hooks in this moment) and checks the price history and saves the new one (actually, it will be first price assigned to the new product). So this is why you had that effect. 

But the chatbot was right: the best solution  is to have a template of the product without any price set so wc price history.

**Comment by SkuterPL** [comment]
There is any chance to clear price history in duplicated product?

**Comment by kkarpieszuk** [comment]
another report on the forum https://wordpress.org/support/topic/disable-copy-meta-history-price-when-product-copy/

I am going to fix this now.

**Comment by SkuterPL** [comment]
Thanks for that. I'm waiting for update

pt., 23 cze 2023, 21:53 użytkownik Konrad Karpieszuk <
***@***.***> napisał:

**Comment by SkuterPL** [comment]
Awesome, thanks for the update!
You are so fast. I will check it in next occasion

pt., 23 cze 2023, 22:08 użytkownik Konrad Karpieszuk <
***@***.***> napisał:

**Comment by kkarpieszuk** [comment]
1.7.4 has been released

**Comment by SkuterPL** [comment]
@kkarpieszuk Can you check why history is copied when I duplicate product with the newest version?

**Comment by kkarpieszuk** [comment]
you you record a screencast showing the issue?

**Comment by SkuterPL** [comment]
@kkarpieszuk can you write me on an email skuterpl@gmail.com I will explain everything
