### ISSUE TITLE
[Feature request] Display history price when product is_on_sale() and has expired _wc_price_history meta

### ISSUE THREAD

**Issue by otr-tomek** [kkarpieszuk/wc-price-history#57]
History price doesnt display when:
- price has changed (post/product has a row in wp_postmeta: _wc_price_history with any date value)
- date is older than in settings days_number

**Comment by kkarpieszuk** [comment]
that should be fixed with the newest release. please update the plugin and re-save the price (change it slightly and change it back)

**Comment by kkarpieszuk** [comment]
I am closing this one. Please feel free to ping if you see the issue still exists
